### ISSUE TITLE
dice - 'output-group-volume' behaves erratic

### ISSUE THREAD

**Issue by dreamcat4** [alsa-project/snd-firewire-ctl-services#91] opened 2022-07-20 22:53 UTC
When setting the volume digitally:

```sh
amixer -c1 cset iface=CARD,name=output-group-volume 127,127,127,127,127,112,127,11,113,11
numid=34,iface=CARD,name='output-group-volume'
  ; type=INTEGER,access=rw----W-,values=10,min=0,max=127,step=1
  : values=127,127,127,127,127,112,127,11,113,11
```

I am listening on headphones 2 (channel 9+10 of the saffire pro 40), and both the position and the values set for that given position... they DO change the volume. It becomes louder or quieter.

However the numbers do not seem to correspond to any predictable or reliable pattern. With one side going quiet. Then the other side. It is clear that the volume is changing. But it is not logical whatsoever

**Comment by takaswie** [comment] 2022-10-29 08:49
Hi @dreamcat4 ,

Thanks for the report, and sorry for the inconvenience and late reply.

Today I start to work for the issue. As you note, I find an issue in the function of
control. But I have no confidence that the issue is what you said since I added
batch of changes to protocols/runtime for dice devices in recent months.

As long as I experienced today, the values of `output-group-volume` control is inverted. I
use Saffire Pro 24 DSP for the test and experienced that when the value is configured
as maximum (0x7f), the sound is silent. When the value is configured as minimum (0x00),
the sound is louder.

I pushed fixes for the issue:
https://github.com/alsa-project/snd-firewire-ctl-services/tree/topic/github/issue/91

I'm glad if you help for debugging ;)

I note that recent changes to runtime for dice
device adds log level option (`-l` or `--log-level`). Currently `debug` level is just
supported. When executing the service program with the option, you can see
logs to help debugging; e.g.

```
$ cargo run --bin snd-dice-ctl-service -- 2 -ldebug
```

The parameters of output group has intermediate expression, `struct OutGroupState`,
we can see the content in the beginning of logs, like:

```
2022-10-29T08:38:24.195544Z DEBUG cache: dice_runtime::focusrite: params=OutGroupState { vols: [127, 127, 127, 0, 127, 0], vol_mutes: [false, false, false, false, false, false], vol_hwctls: [false, false, false, false, false, false], mute_enabled: false, mute_hwctls: [true, true, false, false, true, true], dim_enabled: false, dim_hwctls: [true, true, false, false, false, false], hw_knob_value: 18 } res=Ok(())
```

Corresponding ALSA controls are also found, like:

```
2022-10-29T08:38:24.228293Z DEBUG load:integer:register: core::card_cntr: numid=575 name="output-group-volume" iface=Card device_id=0 subdevice_id=0 index=0
2022-10-29T08:38:24.228372Z DEBUG load:integer:register: core::card_cntr: numid=575 access=READ | WRITE | LOCK | OWNER | USER elem_type=Integer owner=215608 value_count=6 value_min=0 value_max=127 value_step=1
2022-10-29T08:38:24.228437Z DEBUG load:integer:register: core::card_cntr: numid=575 unlock=true res=Ok(())
2022-10-29T08:38:24.228501Z DEBUG load:integer: core::card_cntr: name="output-group-volume" iface=Card device_id=0 subdevice_id=0 index=0 elem_count=1 min=0 max=127 step=1 value_count=6 tlv=None unlock=true res=Ok([ElemId { inner: Boxed { inner: 0x5594fb44f350 }, phantom: PhantomData }])
```

When operating the control, we can see logs below:

```
2022-10-29T08:43:05.428103Z DEBUG event:element: dice_runtime: numid=575 name="output-group-volume" iface=Card device_id=0 subdevice_id=0 index=0
2022-10-29T08:43:05.428426Z DEBUG event:element:value:local: core::card_cntr: numid=575 values="[127, 127, 127, 0, 127, 0]"
2022-10-29T08:43:05.428615Z DEBUG event:element:value:kernel: core::card_cntr: numid=575 values="[124, 127, 127, 0, 127, 0]" res=Ok(())
2022-10-29T08:43:05.433769Z DEBUG event:element:value:hardware: dice_runtime::focusrite: params=OutGroupState { vols: [124, 127, 127, 0, 127, 0], vol_mutes: [false, false, false, false, false, false], vol_hwctls: [false, false, false, false, false, false], mute_enabled: false, mute_hwctls: [true, true, false, false, true, true], dim_enabled: false, dim_hwctls: [true, true, false, false, false, false], hw_knob_value: 18 } res=Ok(())
2022-10-29T08:43:05.434026Z DEBUG event:element:value:hardware: core::card_cntr: numid=575 old_values="[127, 127, 127, 0, 127, 0]" new_values="[124, 127, 127, 0, 127, 0]" res=Ok(true)
```

The log with `event:element:value:kernel` prefix is a request to change by ALSA control
application. The log with `event:element:value:hardware` is actual operation to hardware.

When pushing hardware buttons or adjusting hardware knobs, and the hardware
transfers notification about it, we can see below line:

```
2022-10-29T08:45:42.129744Z DEBUG event:notify: dice_runtime: msg = 0x00200000
```

Then the runtime attempts to cache state of hardware and update ALSA control element,
then it outputs logs with `event:notify` prefix, like:

```
2022-10-29T08:45:42.145572Z DEBUG event:notify:hardware: core::card_cntr: numid=575 values="[124, 127, 127, 0, 127, 0]" res=Ok(true)
2022-10-29T08:45:42.145706Z DEBUG event:notify:kernel: core::card_cntr: numid=575 values="[124, 127, 127, 0, 127, 0]" res=Ok(())
```

**Comment by takaswie** [comment] 2022-11-07 08:52
#135 is merged. Let me close the issue since no reactions from reporter.

**Closed by takaswie** 2022-11-07 08:52 UTC
Labels: bug

**Comment by dreamcat4** [comment] 2022-11-07 09:19
thanks so much @takaswie! sorry i missed the issue updates and did not notice in time to test / check. but will go back to try it at some point in future for the pro40 hardware. after updating my installation here. shall need to first update the crates verisions etc. to be up to date these recent git commits. then can re-test it again.

my apologies for not being around / available for doing that earlier. very grateful for this. kind regards
